dubbo:
  application:
    name: ego-portal
  registry:
    address: zookeeper://39.106.114.169:2181

server:
  port: 8082

# Spring MVC视图解析器
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  profiles:
    active: commons,redis