spring:
  rabbitmq:
    host: 39.106.114.169
    username: root
    password: root
  profiles:
    active: commons,redis

dubbo:
  application:
    name: ego-item
  registry:
    address: zookeeper://39.106.114.169:2181

